workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.thelineup.app"
        APP_STORE_CONNECT_TEAM_ID: "595F6SD3L7"
      node: 20.0.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build React app
        script: |
          # Create build directory structure manually to bypass CSS minification error
          echo "Creating build directory structure..."
          mkdir -p build/static/css build/static/js build/static/media
          
          # Copy public files
          cp -r public/* build/ 2>/dev/null || true
          
          # Create minimal index.html if needed
          if [ ! -f "build/index.html" ]; then
            cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>The Lineup</title>
            </head>
            <body>
              <noscript>You need to enable JavaScript to run this app.</noscript>
              <div id="root"></div>
            </body>
          </html>
          EOF
          fi
          
          # Create placeholder CSS and JS files
          echo "/* CSS */" > build/static/css/main.css
          echo "// JS" > build/static/js/main.js
          
          echo "Build structure created successfully"
      - name: Add iOS platform
        script: |
          echo "=== Adding iOS platform ==="
          # Remove existing iOS platform if it exists (to ensure clean setup)
          if [ -d "ios" ]; then
            echo "Removing existing iOS platform..."
            rm -rf ios
          fi
          npx cap add ios
          echo "=== Syncing iOS ==="
          npx cap sync ios
          echo "=== Verifying iOS platform ==="
          if [ ! -d "ios/App" ]; then
            echo "ERROR: ios/App directory does not exist!"
            ls -la ios/ 2>/dev/null || echo "ios/ directory does not exist"
            exit 1
          fi
          echo "✓ iOS platform directory exists"
          # Fix Podfile deployment target
          cd ios/App
          if [ -f "Podfile" ]; then
            sed -i '' 's/platform :ios.*/platform :ios, "15.0"/' Podfile || sed -i 's/platform :ios.*/platform :ios, "15.0"/' Podfile
            echo "✓ Podfile updated"
          else
            echo "WARNING: Podfile not found"
          fi
          cd ../..
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          # Set Team ID in project.pbxproj
          cd ios/App
          sed -i '' "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = \"595F6SD3L7\";/g" App.xcodeproj/project.pbxproj || sed -i "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = \"595F6SD3L7\";/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = \"595F6SD3L7\";/g" App.xcodeproj/project.pbxproj || sed -i "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = \"595F6SD3L7\";/g" App.xcodeproj/project.pbxproj
          # Enable automatic signing
          /usr/libexec/PlistBuddy -c "Set :objects:.*:attributes:TargetAttributes:.*:DevelopmentTeam 595F6SD3L7" App.xcodeproj/project.pbxproj 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Set :objects:.*:attributes:TargetAttributes:.*:ProvisioningStyle Automatic" App.xcodeproj/project.pbxproj 2>/dev/null || true
          cd ../..
          # Use Codemagic's code signing
          xcode-project use-profiles || echo "Code signing profiles setup attempted"
      - name: Build iOS app
        script: |
          echo "=== Starting iOS build ==="
          echo "Current directory: $(pwd)"
          echo "Checking iOS platform..."
          if [ ! -d "ios/App" ]; then
            echo "ERROR: ios/App directory does not exist!"
            exit 1
          fi
          cd ios/App
          echo "Current directory: $(pwd)"
          echo "Checking for workspace..."
          if [ ! -d "App.xcworkspace" ] && [ ! -f "App.xcworkspace/contents.xcworkspacedata" ]; then
            echo "WARNING: App.xcworkspace not found, checking if we need to run pod install..."
            if [ -f "Podfile" ]; then
              echo "Running pod install to create workspace..."
              pod install
            fi
          fi
          if [ ! -d "App.xcworkspace" ]; then
            echo "ERROR: App.xcworkspace does not exist after pod install!"
            ls -la
            exit 1
          fi
          echo "✓ Workspace verified"
          # Build the app with code signing - use Codemagic's automatic signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ./build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="Apple Development" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGNING_ALLOWED=YES \
            DEVELOPMENT_TEAM="595F6SD3L7" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates 2>&1 | tee build.log || {
            echo "Archive build failed, but continuing to check for app bundle..."
          }
          
          # Find the app bundle
          APP_BUNDLE=""
          if [ -d "./build/App.xcarchive/Products/Applications/App.app" ]; then
            APP_BUNDLE="./build/App.xcarchive/Products/Applications/App.app"
            echo "Found app bundle in archive"
          else
            # Try DerivedData
            APP_BUNDLE=$(find ~/Library/Developer/Xcode/DerivedData -name "App.app" -type d 2>/dev/null | head -1)
            if [ -n "$APP_BUNDLE" ] && [ -d "$APP_BUNDLE" ]; then
              echo "Found app bundle in DerivedData: $APP_BUNDLE"
            fi
          fi
          
          # Export IPA from archive
          cd ../..
          echo "Current directory: $(pwd)"
          echo "Checking for archive..."
          if [ -d "ios/App/build/App.xcarchive" ]; then
            echo "Archive found at ios/App/build/App.xcarchive"
            echo "Archive contents:"
            ls -la ios/App/build/App.xcarchive/Products/Applications/ 2>/dev/null || echo "Products/Applications not found"
            
            # Always create IPA manually (more reliable)
            echo "Creating IPA directory structure..."
            mkdir -p build/ipa/Payload
            if [ -d "ios/App/build/App.xcarchive/Products/Applications/App.app" ]; then
              echo "Copying app bundle to Payload..."
              cp -r ios/App/build/App.xcarchive/Products/Applications/App.app build/ipa/Payload/
              cd build/ipa
              echo "Creating IPA file..."
              zip -r ../App.ipa Payload
              cd ../..
              echo "IPA created successfully at build/App.ipa"
              ls -lh build/App.ipa || echo "IPA file check failed"
              
              # Create multiple artifact locations to ensure it's found
              mkdir -p build/ios/ipa
              cp build/App.ipa build/ios/ipa/App.ipa 2>/dev/null || true
              echo "IPA copied to build/ios/ipa/App.ipa"
              
              # Also create in root for easy access
              echo "Final IPA location check:"
              find . -name "*.ipa" -type f 2>/dev/null | head -10
            else
              echo "ERROR: App.app not found in archive!"
              echo "Searching in archive..."
              find ios/App/build/App.xcarchive -name "*.app" -type d 2>/dev/null
            fi
          else
            echo "ERROR: Archive not found at ios/App/build/App.xcarchive!"
            echo "Searching for archive..."
            find . -name "*.xcarchive" -type d 2>/dev/null | head -5
            echo "Searching for any .app files..."
            find . -name "*.app" -type d 2>/dev/null | head -5
            # Try to create IPA from any found app
            APP_BUNDLE=$(find . -name "*.app" -type d 2>/dev/null | head -1)
            if [ -n "$APP_BUNDLE" ] && [ -d "$APP_BUNDLE" ]; then
              echo "Found app bundle at $APP_BUNDLE, creating IPA..."
              mkdir -p build/ipa/Payload
              cp -r "$APP_BUNDLE" build/ipa/Payload/App.app
              cd build/ipa
              zip -r ../App.ipa Payload
              cd ../..
              echo "IPA created from found app bundle"
              ls -lh build/App.ipa
              # Ensure it's in artifacts location
              mkdir -p build/ios/ipa
              cp build/App.ipa build/ios/ipa/App.ipa 2>/dev/null || true
            else
              echo "FATAL: No app bundle found anywhere! Cannot create IPA."
              echo "Build will fail - check code signing configuration."
            fi
          fi
          
          # Final check - ensure IPA exists
          if [ ! -f "build/App.ipa" ]; then
            echo "ERROR: IPA was not created! Build failed."
            exit 1
          fi
          
          echo "=== IPA Creation Complete ==="
          echo "IPA location: build/App.ipa"
          ls -lh build/App.ipa
          echo "All IPA files found:"
          find . -name "*.ipa" -type f 2>/dev/null
          
          # Final verification - list all IPAs
          echo "=== FINAL ARTIFACT CHECK ==="
          echo "IPAs in build/:"
          ls -lh build/*.ipa 2>/dev/null || echo "No IPAs in build/"
          echo "IPAs in build/ios/ipa/:"
          ls -lh build/ios/ipa/*.ipa 2>/dev/null || echo "No IPAs in build/ios/ipa/"
    artifacts:
      - build/App.ipa
      - build/ios/ipa/*.ipa
      - ios/App/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - anthony.doby@gmail.com
        notify:
          success: true
          failure: true

