// src/utils/badgeLibrary.js

import {
    BADGE_TYPE,
    BADGE_CATEGORY,
    BADGE_RARITY,
  } from "./badgeService";
  
  /**
   * Badge Library - All pre-defined badges
   * Icons are currently emoji-based. For production, upload custom SVG icons to Firebase Storage
   * and update the icon field to use the storage URL.
   */
  export const BADGE_LIBRARY = {
    
    // ==================== FRONT OF HOUSE (FOH) EMPLOYEE BADGES ====================
    
    // Service & Guest Experience
    foh_five_star_service: {
      id: "foh_five_star_service",
      name: "Five-Star Service",
      description: "Consistently delivers exceptional service",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_five_star_service.svg",
      color: "#fbbf24",
    },
    foh_guest_favorite: {
      id: "foh_guest_favorite",
      name: "Guest Favorite",
      description: "Frequently requested by guests",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_guest_favorite.svg",
      color: "#ec4899",
    },
    foh_hospitality_pro: {
      id: "foh_hospitality_pro",
      name: "Hospitality Pro",
      description: "Master of hospitality and guest relations",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 350,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_hospitality_pro.svg",
      color: "#3b82f6",
    },
    foh_calm_under_fire: {
      id: "foh_calm_under_fire",
      name: "Calm Under Fire",
      description: "Maintains composure during busy rushes",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_calm_under_fire.svg",
      color: "#10b981",
    },
    foh_crowd_controller: {
      id: "foh_crowd_controller",
      name: "Crowd Controller",
      description: "Expert at managing busy sections",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_crowd_controller.svg",
      color: "#6366f1",
    },
    foh_table_whisperer: {
      id: "foh_table_whisperer",
      name: "Table Whisperer",
      description: "Intuitive table management skills",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_table_whisperer.svg",
      color: "#8b5cf6",
    },
    foh_vip_certified: {
      id: "foh_vip_certified",
      name: "VIP Certified",
      description: "Certified to handle VIP guests",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_vip_certified.svg",
      color: "#f59e0b",
    },
    foh_allergy_aware: {
      id: "foh_allergy_aware",
      name: "Allergy-Aware Certified",
      description: "Certified in allergy safety protocols",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_allergy_aware.svg",
      color: "#ef4444",
      requiresApproval: true,
    },
    foh_conflict_resolver: {
      id: "foh_conflict_resolver",
      name: "Conflict Resolver",
      description: "Expert at resolving guest issues",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_conflict_resolver.svg",
      color: "#10b981",
    },
    foh_service_recovery_hero: {
      id: "foh_service_recovery_hero",
      name: "Service Recovery Hero",
      description: "Turns negative experiences into positive ones",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_service_recovery_hero.svg",
      color: "#f59e0b",
    },
    
    // Sales & Upsell
    foh_top_seller: {
      id: "foh_top_seller",
      name: "Top Seller",
      description: "Highest sales this month",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_top_seller.svg",
      color: "#fbbf24",
    },
    foh_check_booster: {
      id: "foh_check_booster",
      name: "Check Booster",
      description: "Consistently increases check averages",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_check_booster.svg",
      color: "#10b981",
    },
    foh_dessert_champion: {
      id: "foh_dessert_champion",
      name: "Dessert Champion",
      description: "Top dessert sales",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_dessert_champion.svg",
      color: "#ec4899",
    },
    foh_beverage_upsell_king: {
      id: "foh_beverage_upsell_king",
      name: "Beverage Upsell King/Queen",
      description: "Master of beverage upselling",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_beverage_upsell_king.svg",
      color: "#7c3aed",
    },
    foh_wine_confident: {
      id: "foh_wine_confident",
      name: "Wine Confident",
      description: "Expert wine knowledge and recommendations",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_wine_confident.svg",
      color: "#8b5cf6",
    },
    foh_cocktail_knowledgeable: {
      id: "foh_cocktail_knowledgeable",
      name: "Cocktail Knowledgeable",
      description: "Expert cocktail knowledge",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_cocktail_knowledgeable.svg",
      color: "#3b82f6",
    },
    foh_high_average_check: {
      id: "foh_high_average_check",
      name: "High Average Check",
      description: "Consistently high check averages",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_high_average_check.svg",
      color: "#10b981",
    },
    foh_merch_mover: {
      id: "foh_merch_mover",
      name: "Merch Mover",
      description: "Top merchandise sales",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_merch_mover.svg",
      color: "#f59e0b",
    },
    
    // Reliability & Professionalism
    foh_always_on_time: {
      id: "foh_always_on_time",
      name: "Always On Time",
      description: "Perfect punctuality record",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.ATTENDANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_always_on_time.svg",
      color: "#10b981",
    },
    foh_shift_saver: {
      id: "foh_shift_saver",
      name: "Shift Saver",
      description: "Frequently covers shifts when needed",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_shift_saver.svg",
      color: "#3b82f6",
    },
    foh_double_shift_warrior: {
      id: "foh_double_shift_warrior",
      name: "Double-Shift Warrior",
      description: "Completed 20+ double shifts",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SHIFT,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_double_shift_warrior.svg",
      color: "#6366f1",
    },
    foh_no_call_no_show_free: {
      id: "foh_no_call_no_show_free",
      name: "No-Call-No-Show Free",
      description: "Zero no-call-no-shows in 6 months",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.ATTENDANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_no_call_no_show_free.svg",
      color: "#10b981",
    },
    foh_management_trusted: {
      id: "foh_management_trusted",
      name: "Management Trusted",
      description: "Trusted by management for key responsibilities",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_management_trusted.svg",
      color: "#6366f1",
    },
    foh_closing_captain: {
      id: "foh_closing_captain",
      name: "Closing Captain",
      description: "Expert at closing shifts",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SHIFT,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_closing_captain.svg",
      color: "#1e293b",
    },
    foh_trainer_certified: {
      id: "foh_trainer_certified",
      name: "Trainer Certified",
      description: "Certified to train new employees",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_trainer_certified.svg",
      color: "#8b5cf6",
      requiresApproval: true,
    },
    foh_new_hire_mentor: {
      id: "foh_new_hire_mentor",
      name: "New Hire Mentor",
      description: "Successfully mentored 5+ new hires",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_new_hire_mentor.svg",
      color: "#3b82f6",
    },
    
    // Social & Brand
    foh_guest_mentioned: {
      id: "foh_guest_mentioned",
      name: "Guest Mentioned",
      description: "Mentioned by name in guest review",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_guest_mentioned.svg",
      color: "#ec4899",
    },
    foh_review_shoutout: {
      id: "foh_review_shoutout",
      name: "Review Shout-Out",
      description: "Featured in positive review",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_review_shoutout.svg",
      color: "#f59e0b",
    },
    foh_photo_featured: {
      id: "foh_photo_featured",
      name: "Photo Featured",
      description: "Featured in guest photo",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_photo_featured.svg",
      color: "#8b5cf6",
    },
    foh_social_share_star: {
      id: "foh_social_share_star",
      name: "Social Share Star",
      description: "Featured in social media posts",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_social_share_star.svg",
      color: "#ec4899",
    },
    foh_influencer_friendly: {
      id: "foh_influencer_friendly",
      name: "Influencer Friendly",
      description: "Successfully hosted influencer visits",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_influencer_friendly.svg",
      color: "#fbbf24",
    },
    foh_brand_ambassador: {
      id: "foh_brand_ambassador",
      name: "Brand Ambassador",
      description: "Represents the brand excellently",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/foh_brand_ambassador.svg",
      color: "#f59e0b",
    },
    
    // ==================== BACK OF HOUSE (BOH) EMPLOYEE BADGES ====================
    
    // Skill & Execution
    boh_grill_master: {
      id: "boh_grill_master",
      name: "Grill Master",
      description: "Master of the grill station",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_grill_master.svg",
      color: "#ef4444",
    },
    boh_saute_specialist: {
      id: "boh_saute_specialist",
      name: "Sauté Specialist",
      description: "Expert sauté skills",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_saute_specialist.svg",
      color: "#f97316",
    },
    boh_fry_station_king: {
      id: "boh_fry_station_king",
      name: "Fry Station King/Queen",
      description: "Master of the fry station",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_fry_station_king.svg",
      color: "#f59e0b",
    },
    boh_knife_skills_certified: {
      id: "boh_knife_skills_certified",
      name: "Knife Skills Certified",
      description: "Certified expert knife skills",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_knife_skills_certified.svg",
      color: "#6366f1",
      requiresApproval: true,
    },
    boh_plating_perfectionist: {
      id: "boh_plating_perfectionist",
      name: "Plating Perfectionist",
      description: "Exceptional plating presentation",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_plating_perfectionist.svg",
      color: "#8b5cf6",
    },
    boh_speed_precision: {
      id: "boh_speed_precision",
      name: "Speed & Precision",
      description: "Fast and accurate execution",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_speed_precision.svg",
      color: "#fbbf24",
    },
    boh_consistency_king: {
      id: "boh_consistency_king",
      name: "Consistency King",
      description: "Perfect consistency in execution",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_consistency_king.svg",
      color: "#10b981",
    },
    boh_high_volume_crusher: {
      id: "boh_high_volume_crusher",
      name: "High-Volume Crusher",
      description: "Excels during high-volume rushes",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_high_volume_crusher.svg",
      color: "#ef4444",
    },
    
    // Quality & Safety
    boh_zero_send_backs: {
      id: "boh_zero_send_backs",
      name: "Zero Send-Backs",
      description: "Zero dishes sent back in a month",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_zero_send_backs.svg",
      color: "#10b981",
    },
    boh_clean_station_certified: {
      id: "boh_clean_station_certified",
      name: "Clean Station Certified",
      description: "Always maintains clean station",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_clean_station_certified.svg",
      color: "#3b82f6",
    },
    boh_health_code_hero: {
      id: "boh_health_code_hero",
      name: "Health Code Hero",
      description: "Perfect health code compliance",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_health_code_hero.svg",
      color: "#10b981",
    },
    boh_allergy_safe_certified: {
      id: "boh_allergy_safe_certified",
      name: "Allergy-Safe Certified",
      description: "Certified in allergy-safe preparation",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_allergy_safe_certified.svg",
      color: "#ef4444",
      requiresApproval: true,
    },
    boh_temperature_control_pro: {
      id: "boh_temperature_control_pro",
      name: "Temperature Control Pro",
      description: "Perfect temperature control",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_temperature_control_pro.svg",
      color: "#f97316",
    },
    boh_waste_reduction_champ: {
      id: "boh_waste_reduction_champ",
      name: "Waste Reduction Champ",
      description: "Minimizes food waste",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_waste_reduction_champ.svg",
      color: "#10b981",
    },
    
    // Team & Leadership
    boh_line_leader: {
      id: "boh_line_leader",
      name: "Line Leader",
      description: "Leads the kitchen line effectively",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_line_leader.svg",
      color: "#f59e0b",
    },
    boh_expo_mvp: {
      id: "boh_expo_mvp",
      name: "Expo MVP",
      description: "Most valuable expo player",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_expo_mvp.svg",
      color: "#6366f1",
    },
    boh_calm_during_rush: {
      id: "boh_calm_during_rush",
      name: "Calm During Rush",
      description: "Maintains composure during rushes",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_calm_during_rush.svg",
      color: "#10b981",
    },
    boh_shift_anchor: {
      id: "boh_shift_anchor",
      name: "Shift Anchor",
      description: "Reliable anchor for the team",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_shift_anchor.svg",
      color: "#3b82f6",
    },
    boh_trainer_certified: {
      id: "boh_trainer_certified",
      name: "Trainer Certified",
      description: "Certified to train kitchen staff",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_trainer_certified.svg",
      color: "#8b5cf6",
      requiresApproval: true,
    },
    boh_recipe_guardian: {
      id: "boh_recipe_guardian",
      name: "Recipe Guardian",
      description: "Maintains recipe consistency",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_recipe_guardian.svg",
      color: "#f59e0b",
    },
    boh_systems_thinker: {
      id: "boh_systems_thinker",
      name: "Systems Thinker",
      description: "Improves kitchen systems and efficiency",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_systems_thinker.svg",
      color: "#8b5cf6",
    },
    
    // Performance-Based
    boh_top_rated_dish_creator: {
      id: "boh_top_rated_dish_creator",
      name: "Top-Rated Dish Creator",
      description: "Created most-reviewed dish",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_top_rated_dish_creator.svg",
      color: "#fbbf24",
    },
    boh_menu_mvp: {
      id: "boh_menu_mvp",
      name: "Menu MVP",
      description: "Most valuable menu contributor",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_menu_mvp.svg",
      color: "#6366f1",
    },
    boh_seasonal_special_winner: {
      id: "boh_seasonal_special_winner",
      name: "Seasonal Special Winner",
      description: "Created winning seasonal special",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_seasonal_special_winner.svg",
      color: "#f97316",
    },
    boh_guest_favorite_dish: {
      id: "boh_guest_favorite_dish",
      name: "Guest Favorite Dish",
      description: "Dish frequently mentioned in reviews",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_guest_favorite_dish.svg",
      color: "#ec4899",
    },
    boh_five_star_kitchen_night: {
      id: "boh_five_star_kitchen_night",
      name: "Five-Star Kitchen Night",
      description: "Perfect kitchen performance night",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/boh/boh_five_star_kitchen_night.svg",
      color: "#fbbf24",
    },
    
    // ==================== VALET DRIVER BADGES ====================
    
    // Driving & Care
    valet_scratch_free_record: {
      id: "valet_scratch_free_record",
      name: "Scratch-Free Record",
      description: "Zero scratches or incidents",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_scratch_free_record.svg",
      color: "#10b981",
    },
    valet_zero_incident_driver: {
      id: "valet_zero_incident_driver",
      name: "Zero Incident Driver",
      description: "Zero incidents in 6 months",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_zero_incident_driver.svg",
      color: "#10b981",
    },
    valet_smooth_operator: {
      id: "valet_smooth_operator",
      name: "Smooth Operator",
      description: "Smooth and careful driving",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_smooth_operator.svg",
      color: "#3b82f6",
    },
    valet_luxury_vehicle_certified: {
      id: "valet_luxury_vehicle_certified",
      name: "Luxury Vehicle Certified",
      description: "Certified to handle luxury vehicles",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_luxury_vehicle_certified.svg",
      color: "#f59e0b",
      requiresApproval: true,
    },
    valet_manual_transmission_certified: {
      id: "valet_manual_transmission_certified",
      name: "Manual Transmission Certified",
      description: "Certified to drive manual transmissions",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_manual_transmission_certified.svg",
      color: "#6366f1",
      requiresApproval: true,
    },
    valet_ev_certified: {
      id: "valet_ev_certified",
      name: "EV Certified",
      description: "Certified to handle electric vehicles",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_ev_certified.svg",
      color: "#10b981",
      requiresApproval: true,
    },
    valet_exotic_car_trusted: {
      id: "valet_exotic_car_trusted",
      name: "Exotic Car Trusted",
      description: "Trusted with exotic vehicles",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_exotic_car_trusted.svg",
      color: "#ef4444",
      requiresApproval: true,
    },
    
    // Speed & Efficiency
    valet_fastest_keys: {
      id: "valet_fastest_keys",
      name: "Fastest Keys",
      description: "Fastest key retrieval time",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_fastest_keys.svg",
      color: "#fbbf24",
    },
    valet_peak_hour_pro: {
      id: "valet_peak_hour_pro",
      name: "Peak Hour Pro",
      description: "Excels during peak hours",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_peak_hour_pro.svg",
      color: "#10b981",
    },
    valet_high_volume_handler: {
      id: "valet_high_volume_handler",
      name: "High-Volume Handler",
      description: "Handles high volume efficiently",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_high_volume_handler.svg",
      color: "#6366f1",
    },
    valet_flow_master: {
      id: "valet_flow_master",
      name: "Flow Master",
      description: "Masters traffic flow management",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_flow_master.svg",
      color: "#3b82f6",
    },
    valet_line_optimizer: {
      id: "valet_line_optimizer",
      name: "Line Optimizer",
      description: "Optimizes valet line efficiency",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_line_optimizer.svg",
      color: "#8b5cf6",
    },
    
    // Guest Experience
    valet_polite_professional: {
      id: "valet_polite_professional",
      name: "Polite Professional",
      description: "Consistently polite and professional",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_polite_professional.svg",
      color: "#10b981",
    },
    valet_guest_complimented: {
      id: "valet_guest_complimented",
      name: "Guest Complimented",
      description: "Received guest compliments",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_guest_complimented.svg",
      color: "#ec4899",
    },
    valet_tip_magnet: {
      id: "valet_tip_magnet",
      name: "Tip Magnet",
      description: "Consistently receives tips",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_tip_magnet.svg",
      color: "#fbbf24",
    },
    valet_vip_driver: {
      id: "valet_vip_driver",
      name: "VIP Driver",
      description: "Trusted with VIP guests",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_vip_driver.svg",
      color: "#f59e0b",
    },
    valet_calm_under_pressure: {
      id: "valet_calm_under_pressure",
      name: "Calm Under Pressure",
      description: "Maintains composure in stressful situations",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_calm_under_pressure.svg",
      color: "#10b981",
    },
    
    // Reliability & Trust
    valet_always_on_time: {
      id: "valet_always_on_time",
      name: "Always On Time",
      description: "Perfect punctuality",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.ATTENDANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_always_on_time.svg",
      color: "#10b981",
    },
    valet_manager_trusted: {
      id: "valet_manager_trusted",
      name: "Manager Trusted",
      description: "Trusted by management",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_manager_trusted.svg",
      color: "#6366f1",
    },
    valet_closing_shift_reliable: {
      id: "valet_closing_shift_reliable",
      name: "Closing Shift Reliable",
      description: "Reliable closing shift driver",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SHIFT,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_closing_shift_reliable.svg",
      color: "#1e293b",
    },
    valet_trainer_driver: {
      id: "valet_trainer_driver",
      name: "Trainer Driver",
      description: "Certified to train new drivers",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_trainer_driver.svg",
      color: "#8b5cf6",
      requiresApproval: true,
    },
    valet_safety_first: {
      id: "valet_safety_first",
      name: "Safety First",
      description: "Perfect safety record",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/valet/valet_safety_first.svg",
      color: "#10b981",
    },
    
    // ==================== DINER BADGES ====================
    
    // Activity & Engagement
    diner_first_review: {
      id: "diner_first_review",
      name: "First Review",
      description: "Posted your first review",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.COMMON,
      pointsValue: 50,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_first_review.svg",
      color: "#fbbf24",
    },
    diner_10_reviews: {
      id: "diner_10_reviews",
      name: "10 Reviews",
      description: "Posted 10 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 100,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_10_reviews.svg",
      color: "#f59e0b",
    },
    diner_50_reviews: {
      id: "diner_50_reviews",
      name: "50 Reviews",
      description: "Posted 50 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_50_reviews.svg",
      color: "#d97706",
    },
    diner_100_reviews: {
      id: "diner_100_reviews",
      name: "100 Reviews",
      description: "Posted 100 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_100_reviews.svg",
      color: "#b45309",
    },
    diner_weekly_reviewer: {
      id: "diner_weekly_reviewer",
      name: "Weekly Reviewer",
      description: "Reviews weekly for a month",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_weekly_reviewer.svg",
      color: "#3b82f6",
    },
    diner_consistent_critic: {
      id: "diner_consistent_critic",
      name: "Consistent Critic",
      description: "Reviews consistently for 3 months",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_consistent_critic.svg",
      color: "#6366f1",
    },
    diner_power_reviewer: {
      id: "diner_power_reviewer",
      name: "Power Reviewer",
      description: "Posted 5+ reviews this week",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_power_reviewer.svg",
      color: "#ef4444",
    },
    
    // Exploration
    diner_neighborhood_explorer: {
      id: "diner_neighborhood_explorer",
      name: "Neighborhood Explorer",
      description: "Visited 10+ restaurants in your neighborhood",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_neighborhood_explorer.svg",
      color: "#3b82f6",
    },
    diner_city_hopper: {
      id: "diner_city_hopper",
      name: "City Hopper",
      description: "Visited restaurants across the city",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_city_hopper.svg",
      color: "#6366f1",
    },
    diner_cuisine_collector: {
      id: "diner_cuisine_collector",
      name: "Cuisine Collector",
      description: "Tried 10+ different cuisines",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_cuisine_collector.svg",
      color: "#8b5cf6",
    },
    diner_hidden_gem_finder: {
      id: "diner_hidden_gem_finder",
      name: "Hidden Gem Finder",
      description: "Discovered 5+ hidden gem restaurants",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_hidden_gem_finder.svg",
      color: "#fbbf24",
    },
    diner_grand_opener_attendee: {
      id: "diner_grand_opener_attendee",
      name: "Grand Opener Attendee",
      description: "Attended a grand opening",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_grand_opener_attendee.svg",
      color: "#ec4899",
    },
    diner_soft_launch_insider: {
      id: "diner_soft_launch_insider",
      name: "Soft Launch Insider",
      description: "Attended a soft launch event",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_soft_launch_insider.svg",
      color: "#f59e0b",
    },
    
    // Events & Community
    diner_event_attendee: {
      id: "diner_event_attendee",
      name: "Event Attendee",
      description: "Attended a restaurant event",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.COMMON,
      pointsValue: 100,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_event_attendee.svg",
      color: "#8b5cf6",
    },
    diner_festival_goer: {
      id: "diner_festival_goer",
      name: "Festival Goer",
      description: "Attended a food festival",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_festival_goer.svg",
      color: "#ec4899",
    },
    diner_tasting_night_regular: {
      id: "diner_tasting_night_regular",
      name: "Tasting Night Regular",
      description: "Attended 5+ tasting nights",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_tasting_night_regular.svg",
      color: "#7c3aed",
    },
    diner_popup_supporter: {
      id: "diner_popup_supporter",
      name: "Pop-Up Supporter",
      description: "Supported a pop-up restaurant",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_popup_supporter.svg",
      color: "#f97316",
    },
    diner_charity_diner: {
      id: "diner_charity_diner",
      name: "Charity Diner",
      description: "Attended a charity dining event",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_charity_diner.svg",
      color: "#ec4899",
    },
    diner_restaurant_week_finisher: {
      id: "diner_restaurant_week_finisher",
      name: "Restaurant Week Finisher",
      description: "Completed restaurant week",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_restaurant_week_finisher.svg",
      color: "#fbbf24",
    },
    
    // Credibility & Influence
    diner_helpful_reviewer: {
      id: "diner_helpful_reviewer",
      name: "Helpful Reviewer",
      description: "Received 50+ helpful votes",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/helpful_reviewer.svg",
      color: "#10b981",
    },
    diner_top_rated_reviewer: {
      id: "diner_top_rated_reviewer",
      name: "Top-Rated Reviewer",
      description: "Top-rated reviewer this month",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_top_rated_reviewer.svg",
      color: "#fbbf24",
    },
    diner_trusted_taste: {
      id: "diner_trusted_taste",
      name: "Trusted Taste",
      description: "Your reviews are highly trusted",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_trusted_taste.svg",
      color: "#8b5cf6",
    },
    diner_influencer: {
      id: "diner_influencer",
      name: "Influencer",
      description: "Verified influencer status",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 1000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_influencer.svg",
      color: "#fbbf24",
      requiresApproval: true,
    },
    diner_local_authority: {
      id: "diner_local_authority",
      name: "Local Authority",
      description: "Recognized local dining authority",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_local_authority.svg",
      color: "#6366f1",
    },
    diner_staff_endorsed: {
      id: "diner_staff_endorsed",
      name: "Staff-Endorsed Diner",
      description: "Endorsed by restaurant staff",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/diner_staff_endorsed.svg",
      color: "#10b981",
    },
    
    // ==================== MANAGEMENT/RESTAURANT/COMPANY BADGES ====================
    
    // Management Excellence
    mgmt_excellence_award: {
      id: "mgmt_excellence_award",
      name: "Management Excellence",
      description: "Outstanding management performance",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_excellence_award.svg",
      color: "#6366f1",
    },
    mgmt_team_builder: {
      id: "mgmt_team_builder",
      name: "Team Builder",
      description: "Built and maintained strong team",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_team_builder.svg",
      color: "#3b82f6",
    },
    mgmt_revenue_growth: {
      id: "mgmt_revenue_growth",
      name: "Revenue Growth Leader",
      description: "Led significant revenue growth",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 1000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_revenue_growth.svg",
      color: "#10b981",
    },
    mgmt_guest_satisfaction_champion: {
      id: "mgmt_guest_satisfaction_champion",
      name: "Guest Satisfaction Champion",
      description: "Achieved highest guest satisfaction scores",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_guest_satisfaction_champion.svg",
      color: "#fbbf24",
    },
    mgmt_operational_excellence: {
      id: "mgmt_operational_excellence",
      name: "Operational Excellence",
      description: "Achieved operational excellence",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_operational_excellence.svg",
      color: "#6366f1",
    },
    mgmt_cost_control_master: {
      id: "mgmt_cost_control_master",
      name: "Cost Control Master",
      description: "Excellent cost control management",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_cost_control_master.svg",
      color: "#10b981",
    },
    mgmt_training_excellence: {
      id: "mgmt_training_excellence",
      name: "Training Excellence",
      description: "Excellence in staff training programs",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_training_excellence.svg",
      color: "#8b5cf6",
    },
    mgmt_safety_champion: {
      id: "mgmt_safety_champion",
      name: "Safety Champion",
      description: "Perfect safety record",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/mgmt_safety_champion.svg",
      color: "#10b981",
    },
    
    // Restaurant Achievement Badges
    restaurant_five_star_rating: {
      id: "restaurant_five_star_rating",
      name: "Five-Star Rating",
      description: "Maintained 5-star rating",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_five_star_rating.svg",
      color: "#fbbf24",
    },
    restaurant_top_performer: {
      id: "restaurant_top_performer",
      name: "Top Performer",
      description: "Top performing restaurant in company",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/top_performer.svg",
      color: "#f59e0b",
    },
    restaurant_growth_champion: {
      id: "restaurant_growth_champion",
      name: "Growth Champion",
      description: "Highest growth in company",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_growth_champion.svg",
      color: "#10b981",
    },
    restaurant_guest_favorite: {
      id: "restaurant_guest_favorite",
      name: "Guest Favorite",
      description: "Most favorited restaurant",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_guest_favorite.svg",
      color: "#ec4899",
    },
    restaurant_innovation_award: {
      id: "restaurant_innovation_award",
      name: "Innovation Award",
      description: "Awarded for innovation",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_AWARD,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_innovation_award.svg",
      color: "#fbbf24",
    },
    restaurant_community_champion: {
      id: "restaurant_community_champion",
      name: "Community Champion",
      description: "Outstanding community involvement",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_community_champion.svg",
      color: "#3b82f6",
    },
    restaurant_sustainability_leader: {
      id: "restaurant_sustainability_leader",
      name: "Sustainability Leader",
      description: "Leader in sustainability practices",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_sustainability_leader.svg",
      color: "#10b981",
    },
    
    // Company-Level Badges
    company_best_restaurant: {
      id: "company_best_restaurant",
      name: "Best Restaurant",
      description: "Best restaurant in company",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_AWARD,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/company_best_restaurant.svg",
      color: "#fbbf24",
    },
    company_excellence_award: {
      id: "company_excellence_award",
      name: "Company Excellence Award",
      description: "Awarded by company for excellence",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_AWARD,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/company_excellence_award.svg",
      color: "#f59e0b",
    },
    
    // Legacy badges (keeping existing ones for compatibility)
    review_1: {
      id: "review_1",
      name: "First Review",
      description: "Posted your first review",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.COMMON,
      pointsValue: 50,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/review_1.svg",
      color: "#fbbf24",
    },
    review_10: {
      id: "review_10",
      name: "Reviewer",
      description: "Posted 10 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 100,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/review_10.svg",
      color: "#f59e0b",
    },
    review_50: {
      id: "review_50",
      name: "Critic",
      description: "Posted 50 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/review_50.svg",
      color: "#d97706",
    },
    review_100: {
      id: "review_100",
      name: "Master Critic",
      description: "Posted 100 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/review_100.svg",
      color: "#b45309",
    },
    review_500: {
      id: "review_500",
      name: "Legendary Critic",
      description: "Posted 500 reviews",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.REVIEW,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 2000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/review_500.svg",
      color: "#92400e",
    },
    checkin_1: {
      id: "checkin_1",
      name: "First Visit",
      description: "Checked in for the first time",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CHECK_IN,
      rarity: BADGE_RARITY.COMMON,
      pointsValue: 10,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/checkin_1.svg",
      color: "#3b82f6",
    },
    checkin_10: {
      id: "checkin_10",
      name: "Regular",
      description: "10 check-ins",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CHECK_IN,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 50,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/checkin_10.svg",
      color: "#2563eb",
    },
    checkin_50: {
      id: "checkin_50",
      name: "Loyal Customer",
      description: "50 check-ins",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CHECK_IN,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/checkin_50.svg",
      color: "#1d4ed8",
    },
    sushi_fanatic: {
      id: "sushi_fanatic",
      name: "Sushi Fanatic",
      description: "Visited 30 sushi restaurants this month",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/sushi_fanatic.svg",
      color: "#ef4444",
    },
    mexican_lover: {
      id: "mexican_lover",
      name: "Mexican Lover",
      description: "Visited 30 Mexican restaurants this month",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.CUISINE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/mexican_lover.svg",
      color: "#f97316",
    },
    photo_master: {
      id: "photo_master",
      name: "Photo Master",
      description: "Uploaded 50 photos",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/diner/photo_master.svg",
      color: "#8b5cf6",
    },
    helpful_reviewer: {
      id: "helpful_reviewer",
      name: "Helpful Reviewer",
      description: "Received 100 helpful votes",
      type: BADGE_TYPE.DINER,
      category: BADGE_CATEGORY.SOCIAL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "👍",
      color: "#10b981",
    },
    tenure_newbie: {
      id: "tenure_newbie",
      name: "Newbie",
      description: "Just starting out",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.COMMON,
      pointsValue: 50,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_newbie.svg",
      color: "#84cc16",
      yearsOfService: 0,
    },
    tenure_1: {
      id: "tenure_1",
      name: "1 Year",
      description: "1 year of service",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 100,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_1.svg",
      color: "#fbbf24",
      yearsOfService: 1,
    },
    tenure_2: {
      id: "tenure_2",
      name: "2 Years",
      description: "2 years of service",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_2.svg",
      color: "#f59e0b",
      yearsOfService: 2,
    },
    tenure_5: {
      id: "tenure_5",
      name: "5 Years",
      description: "5 years of service",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_5.svg",
      color: "#d97706",
      yearsOfService: 5,
    },
    tenure_10: {
      id: "tenure_10",
      name: "10 Years",
      description: "10 years of service",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 1000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_10.svg",
      color: "#b45309",
      yearsOfService: 10,
    },
    tenure_20: {
      id: "tenure_20",
      name: "20 Years",
      description: "20 years of service",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.TENURE,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 2000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/tenure_20.svg",
      color: "#92400e",
      yearsOfService: 20,
    },
    top_performer: {
      id: "top_performer",
      name: "Top Performer",
      description: "Top performer this month",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.PERFORMANCE,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 200,
      icon: "🏆",
      color: "#fbbf24",
    },
    perfect_attendance_month: {
      id: "perfect_attendance_month",
      name: "Perfect Attendance",
      description: "Perfect attendance this month",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.ATTENDANCE,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 100,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/perfect_attendance_month.svg",
      color: "#10b981",
    },
    perfect_attendance_year: {
      id: "perfect_attendance_year",
      name: "Perfect Attendance Year",
      description: "Perfect attendance this year",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.ATTENDANCE,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 1000,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/perfect_attendance_year.svg",
      color: "#059669",
    },
    sommelier: {
      id: "sommelier",
      name: "Sommelier",
      description: "Certified wine expert",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/sommelier.svg",
      color: "#7c3aed",
      requiresApproval: true,
    },
    wine_expert: {
      id: "wine_expert",
      name: "Wine Expert",
      description: "Expert knowledge of wine",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 250,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/wine_expert.svg",
      color: "#8b5cf6",
      requiresApproval: true,
    },
    menu_master: {
      id: "menu_master",
      name: "Menu Master",
      description: "Expert knowledge of menu items",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.SKILL,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 150,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/menu_master.svg",
      color: "#3b82f6",
    },
    shift_100: {
      id: "shift_100",
      name: "100 Shifts",
      description: "Completed 100 shifts",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SHIFT,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/shift_100.svg",
      color: "#6366f1",
    },
    night_owl: {
      id: "night_owl",
      name: "Night Owl",
      description: "Worked 50 night shifts",
      type: BADGE_TYPE.EMPLOYEE_SYSTEM,
      category: BADGE_CATEGORY.SHIFT,
      rarity: BADGE_RARITY.UNCOMMON,
      pointsValue: 200,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/night_owl.svg",
      color: "#1e293b",
    },
    employee_of_month: {
      id: "employee_of_month",
      name: "Employee of the Month",
      description: "Awarded by management",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 500,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/employee_of_month.svg",
      color: "#fbbf24",
    },
    outstanding_service: {
      id: "outstanding_service",
      name: "Outstanding Service",
      description: "Awarded by management",
      type: BADGE_TYPE.EMPLOYEE_RESTAURANT,
      category: BADGE_CATEGORY.MANAGER_AWARD,
      rarity: BADGE_RARITY.RARE,
      pointsValue: 300,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/outstanding_service.svg",
      color: "#f59e0b",
    },
    restaurant_excellence: {
      id: "restaurant_excellence",
      name: "Excellence Award",
      description: "Awarded by company",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_AWARD,
      rarity: BADGE_RARITY.EPIC,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/management/restaurant_excellence.svg",
      color: "#fbbf24",
    },
    top_performer_restaurant: {
      id: "top_performer_restaurant",
      name: "Top Performer",
      description: "Top performing restaurant",
      type: BADGE_TYPE.RESTAURANT,
      category: BADGE_CATEGORY.RESTAURANT_ACHIEVEMENT,
      rarity: BADGE_RARITY.LEGENDARY,
      pointsValue: 0,
      icon: "https://storage.googleapis.com/thelineupapp-88c99.firebasestorage.app/badges/foh/top_performer_restaurant.svg",
      color: "#f59e0b",
    },
  };
  
  /**
   * Generate tenure badges for years 1-50
   */
  function generateTenureBadges() {
    const tenureBadges = {};
    
    for (let year = 1; year <= 50; year++) {
      if (year === 1 || year === 2 || year === 5 || year === 10 || year === 20) {
        // Already defined above
        continue;
      }
      
      let rarity = BADGE_RARITY.UNCOMMON;
      let pointsValue = 100 + (year * 10);
      
      if (year >= 25) {
        rarity = BADGE_RARITY.LEGENDARY;
        pointsValue = 2000 + ((year - 25) * 100);
      } else if (year >= 15) {
        rarity = BADGE_RARITY.EPIC;
        pointsValue = 1000 + ((year - 15) * 50);
      } else if (year >= 5) {
        rarity = BADGE_RARITY.RARE;
        pointsValue = 500 + ((year - 5) * 25);
      }
      
      tenureBadges[`tenure_${year}`] = {
        id: `tenure_${year}`,
        name: `${year} Years`,
        description: `${year} years of service`,
        type: BADGE_TYPE.EMPLOYEE_SYSTEM,
        category: BADGE_CATEGORY.TENURE,
        rarity,
        pointsValue,
        icon: "⭐",
        color: year >= 25 ? "#92400e" : year >= 15 ? "#b45309" : year >= 10 ? "#d97706" : "#f59e0b",
        yearsOfService: year,
      };
    }
    
    return tenureBadges;
  }
  
  // Merge generated tenure badges into library
  const generatedTenureBadges = generateTenureBadges();
  Object.assign(BADGE_LIBRARY, generatedTenureBadges);
  
  /**
   * Get badge by ID
   */
  export function getBadgeById(badgeId) {
    return BADGE_LIBRARY[badgeId] || null;
  }
  
  /**
   * Get all badges by type
   */
  export function getBadgesByType(type) {
    return Object.values(BADGE_LIBRARY).filter((badge) => badge.type === type);
  }
  
  /**
   * Get all badges by category
   */
  export function getBadgesByCategory(category) {
    return Object.values(BADGE_LIBRARY).filter((badge) => badge.category === category);
  }
  
  /**
   * Get all employee badges (system + restaurant templates)
   */
  export function getEmployeeBadgeTemplates() {
    return Object.values(BADGE_LIBRARY).filter(
      (badge) =>
        badge.type === BADGE_TYPE.EMPLOYEE_SYSTEM ||
        badge.type === BADGE_TYPE.EMPLOYEE_RESTAURANT
    );
  }
  
  /**
   * Get all diner badges
   */
  export function getDinerBadgeTemplates() {
    return Object.values(BADGE_LIBRARY).filter(
      (badge) => badge.type === BADGE_TYPE.DINER
    );
  }
  
  /**
   * Get all restaurant badges
   */
  export function getRestaurantBadgeTemplates() {
    return Object.values(BADGE_LIBRARY).filter(
      (badge) => badge.type === BADGE_TYPE.RESTAURANT
    );
  }
  
  /**
   * Get manager-awardable badges (restaurant-specific employee badges)
   */
  export function getManagerAwardableBadges() {
    return Object.values(BADGE_LIBRARY).filter(
      (badge) =>
        badge.type === BADGE_TYPE.EMPLOYEE_RESTAURANT ||
        (badge.type === BADGE_TYPE.EMPLOYEE_SYSTEM && badge.requiresApproval)
    );
  }
